const xapp = require('./xapp.config.js');
module.exports = {
    XcxLogin: `${xapp.api_host}/Weixin/getOpenId`,
    UserRegister: `${xapp.api_host}/Weixin/register`,
    BindPhone:`${xapp.api_host}/Weixin/decryptData`,
    UserInfo:`${xapp.api_host}/User/show`,
    //测试点
    TestPoint:`${xapp.api_host}/TestPoint/state`, 
    //回忆
    Memory:`${xapp.api_host}/Memory/store`,
    MemoryIndex:`${xapp.api_host}/Memory/index`,
    MemoryMy:`${xapp.api_host}/Memory/mycollect`,
    MemoryLike:`${xapp.api_host}/Memory/like`,
    MemoryCollect:`${xapp.api_host}/Memory/collect`,
    MemoryDiscuz:`${xapp.api_host}/Memory/discuz`,
    MemoryDLike:`${xapp.api_host}/Memory/discuzLike`,
    MemoryItem:`${xapp.api_host}/Memory/show`,
    Rowner:`${xapp.api_host}/Memory/owner`,
    //题目
    QuestionType:`${xapp.api_host}/QuestionType/index`,
    QuestionIndex:`${xapp.api_host}/Question/index`,
    QuestionShow:`${xapp.api_host}/Question/show`,
    QuestionConfirm:`${xapp.api_host}/Question/confirm`,
    QuestionCollect:`${xapp.api_host}/Question/collect`,
    QuestionDiscuz:`${xapp.api_host}/Question/discuz`,
    QuestionDiscuzLike:`${xapp.api_host}/Question/discuzLike`,
    QuestionPrev:`${xapp.api_host}/Question/Prev`,
    QuestionNext:`${xapp.api_host}/Question/Next`,
    QuestionRecord:`${xapp.api_host}/Question/record`,
    QuestionRemark:`${xapp.api_host}/Question/remark`,
    QuestionExerciseLike:`${xapp.api_host}/Question/exerciseLike`,
    QuestionExerciseStore:`${xapp.api_host}/Question/exerciseStore`,
    QuestionExerciseShow:`${xapp.api_host}/Question/exerciseShow`,
    QuestionExerciseRemark:`${xapp.api_host}/Question/exerciseRemark`,
    QuestionMyWord:`${xapp.api_host}/Question/myWord`,
    QuestionNewWord:`${xapp.api_host}/Question/newWord`,
    //练习
    PracticeList:`${xapp.api_host}/Practice/practice_list`,
    PracticeDetail:`${xapp.api_host}/Practice/practice_detail`,
    PracticeTask:`${xapp.api_host}/Practice/task_detail`,
    PracticeCollect:`${xapp.api_host}/Practice/practiceCollect`,
    PracticeMyCollect:`${xapp.api_host}/Practice/myCollect`,
    //高分
    HighScoreIndex:`${xapp.api_host}/HighScore/index`,
    HighScoreIndexh:`${xapp.api_host}/HighScore/hindex`,
    HighScoreShow:`${xapp.api_host}/HighScore/show`,
    //老师
    FamousIndex:`${xapp.api_host}/FamousTeacher/index`,
    FamousShow:`${xapp.api_host}/FamousTeacher/show`,

    ReserveConsult:`${xapp.api_host}/ReserveConsulting/store`,
    ReserveConsultImg:`${xapp.api_host}/ReserveConsulting/image`,
    ReserveReport:`${xapp.api_host}/ReserveReport/store`,
    ReserveReportImg:`${xapp.api_host}/ReserveReportImg/image`,
    //文章
    Article:`${xapp.api_host}/Article/index`,
    ArticleShow:`${xapp.api_host}/Article/show`,
    ArticleCollect:`${xapp.api_host}/Article/collect`,
    ArticleMyCollect:`${xapp.api_host}/Article/myCollect`,
    //活动
    Course:`${xapp.api_host}/OfflineCourse/index`,
    CourseShow:`${xapp.api_host}/OfflineCourse/show`,
    Activity:`${xapp.api_host}/OfflineActivity/index`,
    ActivityShow:`${xapp.api_host}/OfflineActivity/show`,
    //用户
    HasSign:`${xapp.api_host}/User/hasSign`,
    Sign:`${xapp.api_host}/User/sign`,
    Modified:`${xapp.api_host}/User/modified`,
    //商品
    Good:`${xapp.api_host}/Goods/index`,
    Rgood:`${xapp.api_host}/Goods/recommend`,
    Gshow:`${xapp.api_host}/Goods/show`,
    Igood:`${xapp.api_host}/IntegralGoods/index`,
    Irgood:`${xapp.api_host}/IntegralGoods/recommend`,
    Ishow:`${xapp.api_host}/IntegralGoods/show`,
    //收藏
    CourseCollect:`${xapp.api_host}/OfflineCourse/collect`,
    CourseMyCollect:`${xapp.api_host}/OfflineCourse/mycollect`,
    ActivityCollect:`${xapp.api_host}/OfflineActivity/collect`,
    ActivityMyCollect:`${xapp.api_host}/OfflineActivity/mycollect`,
    //积分
    IntegralOrder:`${xapp.api_host}/IntegralGoods/order`,
    IntegralOwner:`${xapp.api_host}/IntegralGoods/owner`,
    IntegralOshow:`${xapp.api_host}/IntegralGoods/oshow`,
    GoodsOrder:`${xapp.api_host}/Goods/order`,
    GoodsOrders:`${xapp.api_host}/Goods/orders`,
    //vip
    VipMember:`${xapp.api_host}/Vip/member`,
    VipExport:`${xapp.api_host}/Vip/export`,
    VipExchange:`${xapp.api_host}/Vip/exchange`,
    VipHasMember:`${xapp.api_host}/Vip/hasmember`,
    Banner:`${xapp.api_host}/Banner/banner`,
    Fbanner:`${xapp.api_host}/Banner/fbanner`,
    Apply:`${xapp.api_host}/ApplyMaterial/apply`,
    //ddd
    PHCollect:`${xapp.api_host}/Practice/has_pcollect`,

    MHCollect:`${xapp.api_host}/Memory/has_collect`,
    MHLike:`${xapp.api_host}/Memory/has_like`,

    MSearch:`${xapp.api_host}/Memory/search`,
    QHCollect:`${xapp.api_host}/Question/has_collect`,
    QSearch:`${xapp.api_host}/Question/search`,
    MQCollect:`${xapp.api_host}/Question/mycollect`,
    HCArticle:`${xapp.api_host}/Article/has_article`,

    HACollect:`${xapp.api_host}/OfflineActivity/has_collect`,
    HCCollect:`${xapp.api_host}/OfflineCourse/has_collect`,
    VipText:`${xapp.api_host}/Vip/mshow`,
    //dd
    NewWordD:`${xapp.api_host}/NewWord/destory`,
    NewWordP:`${xapp.api_host}/NewWord/prev`,
    NewWordN:`${xapp.api_host}/NewWord/next`,


}  
