const api = require('./api.config.js');
const request = require('../common/request.js');
module.exports = {
    XcxUserInfo: (data) => request(api.XcxUserInfo, data, 'POST'), 
    UserRegister: (data) => request(api.UserRegister, data, 'POST'), 
    
    ReserveConsult:(data) =>request(api.ReserveConsult,data,'POST'),
    ReserveConsultImg:(data) =>request(api.ReserveConsultImg,data,'POST'),
    ReserveReport:(data) =>request(api.ReserveReport,data,'POST'),
    ReserveReportImg:(data) =>request(api.ReserveReportImg,data,'POST'),



    UserInfo: (data) => request(api.UserInfo, data, 'POST'),
    UserSendSMT: (data) => request(api.UserSendSMT, data, 'POST'),
    setCookie: (data) => request(api.setCookie, data, 'POST'),
    UserBind: (data) => request(api.UserBind, data, 'POST'),
    HomeWebsite: (data) => request(api.HomeWebsite, data, 'POST'),
    HomeBanner: (data) => request(api.HomeBanner, data, 'POST'),
    HomeIndex: (data) => request(api.HomeIndex, data, 'POST'),
    HomeAbout: (data) => request(api.HomeAbout, data, 'POST'),
    GoodsRecommend: (data) => request(api.GoodsRecommend, data, 'POST'),
    GoodsAllClassify: (data) => request(api.GoodsAllClassify, data, 'POST'),
    GoodsList: (data) => request(api.GoodsList, data, 'POST'),
    GoodsSearch: (data) => request(api.GoodsSearch, data, 'POST'),
    GoodsInfo: (data) => request(api.GoodsInfo, data, 'POST'),
    AddressLists: (data) => request(api.AddressLists, data, 'POST'),
    AddressMap: (data) => request(api.AddressMap, data, 'POST'),
    AddressAdd: (data) => request(api.AddressAdd, data, 'POST'),
    AddressOne: (data) => request(api.AddressOne, data, 'POST'),
    AddressModify: (data) => request(api.AddressModify, data, 'POST'),
    AddressDel: (data) => request(api.AddressDel, data, 'POST'),
    CartAdd: (data) => request(api.CartAdd, data, 'POST'),
    CartInfo: (data) => request(api.CartInfo, data, 'POST'),
    CartEdit: (data) => request(api.CartEdit, data, 'POST'),
    CollectionList: (data) => request(api.CollectionList, data, 'POST'),
    CollectionAdd: (data) => request(api.CollectionAdd, data, 'POST'),
    CollectionDelete: (data) => request(api.CollectionDelete, data, 'POST'),
    EvaluateList: (data) => request(api.EvaluateList, data, 'POST'),
    EvaluateCreate: (data) => request(api.EvaluateCreate, data, 'POST'),
    CouponList: (data) => request(api.CouponList, data, 'POST'),
    CouponExchange: (data) => request(api.CouponExchange, data, 'POST'),
    CouponAvList: (data) => request(api.CouponAvList, data, 'POST'),
    CouponUse: (data) => request(api.CouponUse, data, 'POST'),
    OrderList: (data, options) => request(api.OrderList, data, 'POST', options),
    OrderCancel: (data) => request(api.OrderCancel, data, 'POST'),
    OrderRefund: (data) => request(api.OrderRefund, data, 'POST'),
    OrderRefundGood: (data) => request(api.OrderRefundGood, data, 'POST'),
    OrderGet: (data) => request(api.OrderGet, data, 'POST'),
    OrderPrepareByCart: (data) => request(api.OrderPrepareByCart, data, 'POST'),
    OrderPrepare: (data) => request(api.OrderPrepare, data, 'POST'),
    OrderSetCoupon: (data) => request(api.OrderSetCoupon, data, 'POST'),
    OrderDelCoupon: (data) => request(api.OrderDelCoupon, data, 'POST'),
    OrderUpdateAddress: (data) => request(api.OrderUpdateAddress, data, 'POST'),
    OrderUpdateRemark: (data) => request(api.OrderUpdateRemark, data, 'POST'),
    OrderUpdatePayMethod: (data) => request(api.OrderUpdatePayMethod, data, 'POST'),
    OrderCreate: (data) => request(api.OrderCreate, data, 'POST'),
    OrderPerpareInfo: (data) => request(api.OrderPerpareInfo, data, 'POST'),
    OrderInfo: (data) => request(api.OrderInfo, data, 'POST'),
    OrderExpress: (data) => request(api.OrderExpress, data, 'POST'),
    OrderUpdateRefundInfo: (data) => request(api.OrderUpdateRefundInfo, data, 'POST'),
    orderTypeCount: (data) => request(api.orderTypeCount, data, 'POST'),
    orderSetbean: (data) => request(api.orderSetbean, data, 'POST'),//五号豆
    orderSetticket: (data) => request(api.orderSetticket, data, 'POST'),//五号券
    orderDelbean: (data) => request(api.orderDelbean, data, 'POST'),//不使用五号豆
    orderDelticket: (data) => request(api.orderDelticket, data, 'POST'),//不使用五号券
    PayCall: (data) => request(api.PayCall, data, 'POST'),
    FuncExpress: (data) => request(api.FuncExpress, data, 'POST'),
    getMessage: (data) => request(api.getMessage, data, 'POST'),
    getMessageLists: (data) => request(api.getMessageLists, data, 'POST'),
    setMessageread: (data) => request(api.setMessageread, data, 'POST'),
    changeNickname: (data) => request(api.changeNickname, data, 'POST'),//设置个人信息 -- 修改昵称
    setCard: (data) => request(api.setCard, data, 'POST'),//设置个人信息 --身份证
    setSex: (data) => request(api.setSex, data, 'POST'),//设置个人信息 --性别
    sendsmPhone: (data) => request(api.sendsmPhone, data, 'POST'),//绑定新的手机号码发送验证码
    changePhone: (data) => request(api.changePhone, data, 'POST'),//绑定新的手机号码
    hotWord: (data) => request(api.hotWord, data, 'POST'),//搜索推荐热词
    beanList: (data) => request(api.beanList, data, 'POST'),//五号豆使用记录
    ticketAmount: (data) => request(api.ticketAmount, data, 'POST'),//五号券总量
    ticketList: (data) => request(api.ticketList, data, 'POST'),//五号券明细
    addOrder: (data) => request(api.addOrder, data, 'POST'),//五号券充值生成订单
    canshWithdraw: (data) => request(api.canshWithdraw, data, 'POST'),//五号券可以提现
    canshConfirm: (data) => request(api.canshConfirm, data, 'POST'),//五号券提现
    uploadImg: (data) => request(api.uploadImg, data, 'POST'),//上传图片
    addEditInfo: (data) => request(api.addEditInfo, data, 'POST','application/json'),//我的商家提交修改
    getBusinessInfo: (data) => request(api.getBusinessInfo, data,'POST'),//获取我的商家信息
}